SELECT NOME
      ,ANO
FROM FILMES;

SELECT NOME
      ,ANO
	  ,DURACAO
FROM FILMES
ORDER BY ANO ASC;

SELECT NOME
      ,ANO
	  ,DURACAO
FROM FILMES
WHERE NOME = 'De Volta para o Futuro';

SELECT NOME
      ,ANO
	  ,DURACAO
FROM FILMES
WHERE ANO = 1997;

SELECT NOME
      ,ANO
	  ,DURACAO
FROM FILMES
WHERE ANO > 2000;

SELECT NOME
      ,ANO
	  ,DURACAO
FROM FILMES
WHERE DURACAO BETWEEN 101 AND 149
ORDER BY DURACAO ASC;

SELECT ANO
	  ,COUNT(*) QUANTIDADE
FROM FILMES
GROUP BY ANO
ORDER BY QUANTIDADE DESC;

SELECT PRIMEIRONOME
     , ULTIMONOME
	 , GENERO
FROM ATORES 
WHERE GENERO = 'M';

SELECT A.NOME
     , B.GENERO
FROM FILMES A 
INNER JOIN FILMESGENERO C ON A.ID = C.IDFILME 
INNER JOIN GENEROS B ON B.ID=C.IDGENERO;

SELECT A.NOME
     , B.GENERO
FROM FILMES A 
INNER JOIN FILMESGENERO C ON A.ID = C.IDFILME 
INNER JOIN GENEROS B ON B.ID=C.IDGENERO
WHERE B.GENERO = 'Mistério';


SELECT A.NOME
     , B.PRIMEIRONOME
	 , B.ULTIMONOME
	 ,C.PAPEL
FROM FILMES A 
INNER JOIN ELENCOFILME C ON A.ID = C.IDFILME 
INNER JOIN ATORES	 B ON B.ID=C.IDATOR;






